services:
  backend:
    build: .
    container_name: django_backend
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_ENV: development
      DJANGO_BASE_URL: inorental-backend/
      DATABASE_NAME: inorental_db
      DATABASE_USER: django_user
      DATABASE_PASSWORD: django_password
      DATABASE_HOST: db
      DATABASE_PORT: 3306

volumes:
  db_data:
